# Generated by Django 4.2.3 on 2023-07-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cRT',
            new_name='cart',
        ),
    ]
