# Generated by Django 4.2.3 on 2023-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_quantity_order_driver_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
